name: Update events from VK

on:
  schedule:
    - cron: '0 */6 * * *'   # каждые 6 ч
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Python deps
      run: |
        pip install requests pandas geopy python-dotenv

    - name: Run scraper
      env:
        VK_TOKEN: ${{ secrets.VK_TOKEN }}
      run: python scrape_meow.py

    - name: Commit updated events.json
      run: |
        git config --global user.name  "github-actions"
        git config --global user.email "actions@github.com"
        git add events.json
        git commit -m "auto: update events" || echo "nothing to commit"
        git push
