name: Update events.json

on:
  schedule:
    - cron: "0 */6 * * *"   # каждые 6 часов
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate events.json
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          # опционально: VK_DOMAIN, VK_MAX_POSTS, YEAR_DEFAULT — тоже можно вынести в Secrets/Vars
          YANDEX_KEY: ${{ secrets.YANDEX_KEY }}
          NOMINATIM_USER_AGENT: "meowafisha-bot"
          ARCGIS_MIN_DELAY: "1.0"
          YANDEX_MIN_DELAY: "1.0"
          NOMINATIM_MIN_DELAY: "1.0"
          GEOCODE_SAVE_LOG: "1"
        run: |
          python fetch_events.py

      - name: Commit & push changes (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: update events.json & geocode cache"
            git push
          else
            echo "No changes."
          fi

