name: Update events.json

on:
  schedule:
    - cron: "0 */6 * * *"   # каждые 6ч
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingest (no DB in CI)
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          VK_DOMAIN: meowafisha
        run: |
          python server/worker/vk_ingest.py
          test -f www/events.json && echo "events.json ok"

      - name: Commit updated events.json
        run: |
          git config --global user.name  "github-actions"
          git config --global user.email "actions@github.com"
          git add www/events.json data/geocode_cache.json || true
          git commit -m "auto: update events.json" || echo "nothing to commit"
          git push
